name: marti_notas
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0' # Asegúrate de que el SDK sea compatible con las versiones de los paquetes

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # Agrega las dependencias de Firebase
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_messaging: ^16.0.3
  firebase_storage: ^13.0.3
  cloud_functions: ^6.0.3

  # Agrega la dependencia para hacer llamadas a tu backend
  http: ^1.1.0

  # Notificaciones locales
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  
  # Formateo de fechas
  intl: ^0.18.1
  
  # Manejo de estado
  provider: ^6.1.1
  
  # Lanzador de URLs (para abrir enlaces)
  url_launcher: ^6.2.2
  
  # Selector de archivos e imágenes
  image_picker: ^1.2.0
  # file_picker actualizado a versión compatible con embedding v2
  file_picker: ^10.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutterfire_cli: ^1.3.1
  mocktail: ^1.0.3
  fake_cloud_firestore: ^4.0.0

  # Dependencia para personalizar íconos
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo notas.png"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/logo notas.png
